// Часто используемые смайлики с ключевыми словами для поиска.
export interface EmojiItem {
  e: string
  k: string
}

export const EMOJIS: EmojiItem[] = [
  { e: '😀', k: 'smile happy joy улыбка радость' },
  { e: '😁', k: 'grin smile teeth ухмылка' },
  { e: '😂', k: 'laugh cry tears смех слёзы' },
  { e: '🤣', k: 'rofl laugh смех кат' },
  { e: '😊', k: 'blush smile shy улыбка смущение' },
  { e: '😇', k: 'angel innocent ангел' },
  { e: '🙂', k: 'smile neutral обычная улыбка' },
  { e: '🙃', k: 'upside down перевёрнутый' },
  { e: '😉', k: 'wink подмигивание' },
  { e: '😌', k: 'relieved спокойствие' },
  { e: '😍', k: 'heart eyes love влюблённость сердечки' },
  { e: '🥰', k: 'love hearts влюблён' },
  { e: '😘', k: 'kiss blow поцелуй' },
  { e: '😗', k: 'kiss поцелуй' },
  { e: '😋', k: 'yum tasty вкусно' },
  { e: '😛', k: 'tongue язык' },
  { e: '😜', k: 'crazy wink tongue придурок язык' },
  { e: '🤪', k: 'crazy безумный' },
  { e: '😝', k: 'squint tongue язык' },
  { e: '🤑', k: 'money деньги богатство' },
  { e: '🤗', k: 'hug объятия' },
  { e: '🤭', k: 'hush cover mouth тихо молчание' },
  { e: '🤫', k: 'shh quiet тише' },
  { e: '🤔', k: 'think thinking задумчивый думает' },
  { e: '🤐', k: 'zipper mouth молния рот' },
  { e: '🤨', k: 'raised eyebrow сомнение' },
  { e: '😐', k: 'neutral равнодушный' },
  { e: '😑', k: 'expressionless без эмоций' },
  { e: '😶', k: 'no mouth молчание' },
  { e: '😏', k: 'smirk ухмылка хитрый' },
  { e: '😒', k: 'unamused недовольный' },
  { e: '🙄', k: 'roll eyes закатить глаза' },
  { e: '😬', k: 'grimace неловко' },
  { e: '🤥', k: 'liar nose пиноккио врун' },
  { e: '😔', k: 'pensive грусть' },
  { e: '😪', k: 'sleepy сонный' },
  { e: '🤤', k: 'drool слюни хочу' },
  { e: '😴', k: 'sleep спит zzz' },
  { e: '😷', k: 'mask маска больной' },
  { e: '🤒', k: 'sick thermometer больной температура' },
  { e: '🤕', k: 'hurt bandage травма бинт' },
  { e: '🤢', k: 'nausea тошнота блевать' },
  { e: '🤮', k: 'vomit блевать' },
  { e: '🥵', k: 'hot жарко пот' },
  { e: '🥶', k: 'cold замёрз' },
  { e: '😵', k: 'dizzy голова кругом' },
  { e: '🤯', k: 'mind blown взрыв мозга' },
  { e: '😎', k: 'cool sunglasses крутой очки' },
  { e: '🥳', k: 'party праздник торт' },
  { e: '😅', k: 'sweat smile пот смех' },
  { e: '😓', k: 'sweat грусть пот' },
  { e: '🥺', k: 'pleading puppy просьба щенок' },
  { e: '😢', k: 'cry плачет' },
  { e: '😭', k: 'sob рыдает' },
  { e: '😱', k: 'scream ужас крик' },
  { e: '😖', k: 'confounded смущён' },
  { e: '😣', k: 'persevere страдание' },
  { e: '😞', k: 'disappointed разочарован' },
  { e: '😓', k: 'downcast пот' },
  { e: '😩', k: 'weary устал' },
  { e: '😫', k: 'tired устал' },
  { e: '🥱', k: 'yawn зевает' },
  { e: '😤', k: 'steam nose злость пар' },
  { e: '😡', k: 'angry злой красный' },
  { e: '😠', k: 'angry злой' },
  { e: '🤬', k: 'cursing swear мат ругается' },
  { e: '😈', k: 'devil evil злодей' },
  { e: '👿', k: 'devil evil злодей' },
  { e: '💀', k: 'skull череп смерть' },
  { e: '💩', k: 'poop какашка' },
  { e: '🤡', k: 'clown клоун' },
  { e: '👻', k: 'ghost призрак' },
  { e: '👽', k: 'alien пришелец' },
  { e: '🤖', k: 'robot робот' },
  { e: '😺', k: 'cat smile кот' },
  { e: '😸', k: 'cat smile кот' },
  { e: '😹', k: 'cat laugh кот' },
  { e: '🙈', k: 'see no evil обезьяна не вижу' },
  { e: '🙉', k: 'hear no evil обезьяна не слышу' },
  { e: '🙊', k: 'speak no evil обезьяна молчу' },
  { e: '👍', k: 'thumbs up like лайк ок хорошо' },
  { e: '👎', k: 'thumbs down dislike дизлайк плохо' },
  { e: '👌', k: 'ok perfect ок супер' },
  { e: '🤌', k: 'pinched fingers итальянский жест' },
  { e: '🤏', k: 'pinching tiny чуть-чуть мало' },
  { e: '✌️', k: 'victory мир победа' },
  { e: '🤞', k: 'crossed fingers удача на удачу' },
  { e: '🤟', k: 'love you жест люблю' },
  { e: '🤘', k: 'rock horns рок метал' },
  { e: '🤙', k: 'call me позвони' },
  { e: '👈', k: 'point left влево' },
  { e: '👉', k: 'point right вправо' },
  { e: '👆', k: 'point up вверх' },
  { e: '👇', k: 'point down вниз' },
  { e: '☝️', k: 'point up вверх' },
  { e: '👋', k: 'wave hello bye привет пока' },
  { e: '🤚', k: 'hand raised рука' },
  { e: '🖐️', k: 'hand рука' },
  { e: '✋', k: 'hand stop стоп рука' },
  { e: '🖖', k: 'vulcan vulcan салют' },
  { e: '👏', k: 'clap applause аплодисменты' },
  { e: '🙌', k: 'raise hands руки вверх ура' },
  { e: '🤝', k: 'handshake рукопожатие' },
  { e: '🙏', k: 'pray please спасибо пожалуйста' },
  { e: '💪', k: 'muscle сила бицепс' },
  { e: '🦾', k: 'mechanical arm робот рука' },
  { e: '🦵', k: 'leg нога' },
  { e: '🦶', k: 'foot ступня' },
  { e: '👂', k: 'ear ухо' },
  { e: '👃', k: 'nose нос' },
  { e: '👀', k: 'eyes глаза смотрю' },
  { e: '👁️', k: 'eye глаз' },
  { e: '🧠', k: 'brain мозг ум' },
  { e: '🫀', k: 'heart органы сердце' },
  { e: '❤️', k: 'red heart любовь сердце' },
  { e: '🧡', k: 'orange heart сердце' },
  { e: '💛', k: 'yellow heart сердце' },
  { e: '💚', k: 'green heart сердце' },
  { e: '💙', k: 'blue heart сердце' },
  { e: '💜', k: 'purple heart сердце' },
  { e: '🖤', k: 'black heart сердце' },
  { e: '🤍', k: 'white heart сердце' },
  { e: '💔', k: 'broken heart разбитое сердце' },
  { e: '❤️‍🔥', k: 'heart fire сердце огонь' },
  { e: '💯', k: 'hundred 100 сто топ' },
  { e: '💢', k: 'anger злость' },
  { e: '💥', k: 'boom explosion взрыв' },
  { e: '💫', k: 'dizzy stars звёзды' },
  { e: '💦', k: 'sweat drops капли вода' },
  { e: '💨', k: 'dash дым бег' },
  { e: '🕳️', k: 'hole дыра' },
  { e: '💬', k: 'speech bubble речь чат' },
  { e: '🗨️', k: 'speech bubble чат' },
  { e: '🗯️', k: 'anger bubble злость' },
  { e: '💭', k: 'thought bubble мысли' },
  { e: '💤', k: 'zzz сон' },
  { e: '🔥', k: 'fire огонь жара' },
  { e: '✨', k: 'sparkles искры блеск' },
  { e: '⭐', k: 'star звезда' },
  { e: '🌟', k: 'glowing star звезда' },
  { e: '🎉', k: 'party popper праздник конфетти' },
  { e: '🎊', k: 'confetti праздник' },
  { e: '🎁', k: 'gift подарок' },
  { e: '🎈', k: 'balloon шарик' },
  { e: '🎂', k: 'cake торт день рождения' },
  { e: '🍰', k: 'cake торт' },
  { e: '🍕', k: 'pizza пицца' },
  { e: '🍔', k: 'burger бургер' },
  { e: '🍟', k: 'fries картошка' },
  { e: '🌭', k: 'hotdog хотдог' },
  { e: '🍿', k: 'popcorn попкорн' },
  { e: '🥓', k: 'bacon бекон' },
  { e: '🍗', k: 'chicken курица' },
  { e: '🍩', k: 'donut пончик' },
  { e: '🍪', k: 'cookie печенье' },
  { e: '🍫', k: 'chocolate шоколад' },
  { e: '🍺', k: 'beer пиво' },
  { e: '🍻', k: 'beers пиво' },
  { e: '🥂', k: 'cheers тост бокалы' },
  { e: '🍷', k: 'wine вино' },
  { e: '☕', k: 'coffee кофе' },
  { e: '🍵', k: 'tea чай' },
  { e: '🥤', k: 'drink напиток' },
  { e: '⚽', k: 'football футбол' },
  { e: '🏀', k: 'basketball баскетбол' },
  { e: '🏈', k: 'football american американский футбол' },
  { e: '⚾', k: 'baseball бейсбол' },
  { e: '🎾', k: 'tennis теннис' },
  { e: '🎮', k: 'game controller игры' },
  { e: '🎯', k: 'target цель' },
  { e: '🎲', k: 'dice кости игра' },
  { e: '♟️', k: 'chess шахматы' },
  { e: '🏆', k: 'trophy кубок победа' },
  { e: '🥇', k: 'gold медаль золото' },
  { e: '🥈', k: 'silver медаль серебро' },
  { e: '🥉', k: 'bronze медаль бронза' },
  { e: '🚀', k: 'rocket ракета полёт run' },
  { e: '✈️', k: 'plane самолёт' },
  { e: '🚗', k: 'car машина' },
  { e: '🚕', k: 'taxi такси' },
  { e: '🚌', k: 'bus автобус' },
  { e: '🚲', k: 'bike велосипед' },
  { e: '🏍️', k: 'motorcycle мотоцикл' },
  { e: '🚂', k: 'train поезд' },
  { e: '🚢', k: 'ship корабль' },
  { e: '⛵', k: 'sailboat лодка' },
  { e: '🏠', k: 'house дом' },
  { e: '🏢', k: 'building здание офис' },
  { e: '🏰', k: 'castle замок' },
  { e: '🗼', k: 'tower башня' },
  { e: '🌍', k: 'earth планета мир' },
  { e: '🌙', k: 'moon луна' },
  { e: '☀️', k: 'sun солнце' },
  { e: '🌈', k: 'rainbow радуга' },
  { e: '🌧️', k: 'rain дождь' },
  { e: '⛈️', k: 'storm гроза' },
  { e: '❄️', k: 'snow снег' },
  { e: '⚡', k: 'lightning молния' },
  { e: '🌊', k: 'wave волна' },
  { e: '🔥', k: 'fire огонь' },
  { e: '🌵', k: 'cactus кактус' },
  { e: '🌸', k: 'flower цветок сакура' },
  { e: '🌺', k: 'hibiscus цветок' },
  { e: '🌻', k: 'sunflower подсолнух' },
  { e: '🌹', k: 'rose роза' },
  { e: '🍀', k: 'clover клевер удача' },
  { e: '🍁', k: 'maple leaf лист' },
  { e: '🎃', k: 'pumpkin тыква хэллоуин' },
  { e: '👑', k: 'crown корона' },
  { e: '💎', k: 'gem бриллиант' },
  { e: '💰', k: 'money bag деньги' },
  { e: '💸', k: 'money fly деньги' },
  { e: '📱', k: 'phone телефон' },
  { e: '💻', k: 'laptop компьютер' },
  { e: '⌨️', k: 'keyboard клавиатура' },
  { e: '🖥️', k: 'monitor монитор' },
  { e: '🖱️', k: 'mouse мышь' },
  { e: '🔔', k: 'bell звонок' },
  { e: '🔕', k: 'bell off без звука' },
  { e: '📢', k: 'loudspeaker громкоговоритель' },
  { e: '📣', k: 'megaphone мегафон' },
  { e: '🔒', k: 'lock замок закрыто' },
  { e: '🔓', k: 'unlock открыто' },
  { e: '🔑', k: 'key ключ' },
  { e: '🛡️', k: 'shield щит защита' },
  { e: '⚔️', k: 'swords мечи' },
  { e: '🗡️', k: 'dagger кинжал' },
  { e: '🔫', k: 'gun пистолет' },
  { e: '💣', k: 'bomb бомба' },
  { e: '🎯', k: 'target цель' },
  { e: '🔧', k: 'wrench ключ инструмент' },
  { e: '🔨', k: 'hammer молоток' },
  { e: '🛠️', k: 'tools инструменты' },
  { e: '📚', k: 'books книги' },
  { e: '📖', k: 'book книга' },
  { e: '✏️', k: 'pencil карандаш' },
  { e: '📝', k: 'memo заметка' },
  { e: '📌', k: 'pin булавка' },
  { e: '📎', k: 'paperclip скрепка' },
  { e: '✂️', k: 'scissors ножницы' },
  { e: '🧹', k: 'broom метла уборка' },
  { e: '🧽', k: 'sponge губка' },
  { e: '🛒', k: 'cart тележка покупки' },
  { e: '🎵', k: 'note музыка' },
  { e: '🎶', k: 'notes музыка' },
  { e: '🎧', k: 'headphones наушники' },
  { e: '🎤', k: 'mic микрофон' },
  { e: '🎸', k: 'guitar гитара' },
  { e: '🥁', k: 'drum барабан' },
  { e: '🎹', k: 'piano пианино' },
  { e: '🎬', k: 'clapper кино фильм' },
  { e: '🎥', k: 'camera камера кино' },
  { e: '📷', k: 'camera фото' },
  { e: '📸', k: 'camera flash фото' },
  { e: '🖼️', k: 'picture картина' },
  { e: '🎨', k: 'palette палитра искусство' },
  { e: '🧩', k: 'puzzle пазл' },
  { e: '🚦', k: 'traffic light светофор' },
  { e: '🏁', k: 'flag флаг финиш' },
  { e: '🎗️', k: 'ribbon лента' },
  { e: '🧿', k: 'nazar амулет глаз' },
  { e: '🫡', k: 'salute честь' },
  { e: '🫠', k: 'melting тает' },
  { e: '🫣', k: 'peek подсматривает' },
  { e: '🥹', k: 'tears smile слёзы улыбка' },
  { e: '❤️‍🩹', k: 'heart healing сердце' },
  { e: '😮‍💨', k: 'exhale выдох' },
  { e: '🤗', k: 'hug объятия' },
  { e: '🤩', k: 'star eyes восторг' },
]

// Поиск смайликов по ключевым словам (регистронезависимый, без диакритики).
export function searchEmojis(query: string, limit = 80): EmojiItem[] {
  const q = query.trim().toLowerCase()
  if (!q) return EMOJIS.slice(0, limit)
  return EMOJIS.filter((it) => it.k.toLowerCase().includes(q)).slice(0, limit)
}
