// Часто используемые смайлики с ключевыми словами для поиска — 1:1 с web/src/utils/emojis.ts
library;

class EmojiItem {
  final String e;
  final String k;
  const EmojiItem({required this.e, required this.k});
}

const List<EmojiItem> emojis = [
  EmojiItem(e: '😀', k: 'smile happy joy улыбка радость'),
  EmojiItem(e: '😁', k: 'grin smile teeth ухмылка'),
  EmojiItem(e: '😂', k: 'laugh cry tears смех слёзы'),
  EmojiItem(e: '🤣', k: 'rofl laugh смех кат'),
  EmojiItem(e: '😊', k: 'blush smile shy улыбка смущение'),
  EmojiItem(e: '😇', k: 'angel innocent ангел'),
  EmojiItem(e: '🙂', k: 'smile neutral обычная улыбка'),
  EmojiItem(e: '🙃', k: 'upside down перевёрнутый'),
  EmojiItem(e: '😉', k: 'wink подмигивание'),
  EmojiItem(e: '😌', k: 'relieved спокойствие'),
  EmojiItem(e: '😍', k: 'heart eyes love влюблённость сердечки'),
  EmojiItem(e: '🥰', k: 'love hearts влюблён'),
  EmojiItem(e: '😘', k: 'kiss blow поцелуй'),
  EmojiItem(e: '😗', k: 'kiss поцелуй'),
  EmojiItem(e: '😋', k: 'yum tasty вкусно'),
  EmojiItem(e: '😛', k: 'tongue язык'),
  EmojiItem(e: '😜', k: 'crazy wink tongue придурок язык'),
  EmojiItem(e: '🤪', k: 'crazy безумный'),
  EmojiItem(e: '😝', k: 'squint tongue язык'),
  EmojiItem(e: '🤑', k: 'money деньги богатство'),
  EmojiItem(e: '🤗', k: 'hug объятия'),
  EmojiItem(e: '🤭', k: 'hush cover mouth тихо молчание'),
  EmojiItem(e: '🤫', k: 'shh quiet тише'),
  EmojiItem(e: '🤔', k: 'think thinking задумчивый думает'),
  EmojiItem(e: '🤐', k: 'zipper mouth молния рот'),
  EmojiItem(e: '🤨', k: 'raised eyebrow сомнение'),
  EmojiItem(e: '😐', k: 'neutral равнодушный'),
  EmojiItem(e: '😑', k: 'expressionless без эмоций'),
  EmojiItem(e: '😶', k: 'no mouth молчание'),
  EmojiItem(e: '😏', k: 'smirk ухмылка хитрый'),
  EmojiItem(e: '😒', k: 'unamused недовольный'),
  EmojiItem(e: '🙄', k: 'roll eyes закатить глаза'),
  EmojiItem(e: '😬', k: 'grimace неловко'),
  EmojiItem(e: '🤥', k: 'liar nose пиноккио врун'),
  EmojiItem(e: '😔', k: 'pensive грусть'),
  EmojiItem(e: '😪', k: 'sleepy сонный'),
  EmojiItem(e: '🤤', k: 'drool слюни хочу'),
  EmojiItem(e: '😴', k: 'sleep спит zzz'),
  EmojiItem(e: '😷', k: 'mask маска больной'),
  EmojiItem(e: '🤒', k: 'sick thermometer больной температура'),
  EmojiItem(e: '🤕', k: 'hurt bandage травма бинт'),
  EmojiItem(e: '🤢', k: 'nausea тошнота блевать'),
  EmojiItem(e: '🤮', k: 'vomit блевать'),
  EmojiItem(e: '🥵', k: 'hot жарко пот'),
  EmojiItem(e: '🥶', k: 'cold замёрз'),
  EmojiItem(e: '😵', k: 'dizzy голова кругом'),
  EmojiItem(e: '🤯', k: 'mind blown взрыв мозга'),
  EmojiItem(e: '😎', k: 'cool sunglasses крутой очки'),
  EmojiItem(e: '🥳', k: 'party праздник торт'),
  EmojiItem(e: '😅', k: 'sweat smile пот смех'),
  EmojiItem(e: '😓', k: 'sweat грусть пот'),
  EmojiItem(e: '🥺', k: 'pleading puppy просьба щенок'),
  EmojiItem(e: '😢', k: 'cry плачет'),
  EmojiItem(e: '😭', k: 'sob рыдает'),
  EmojiItem(e: '😱', k: 'scream ужас крик'),
  EmojiItem(e: '😖', k: 'confounded смущён'),
  EmojiItem(e: '😣', k: 'persevere страдание'),
  EmojiItem(e: '😞', k: 'disappointed разочарован'),
  EmojiItem(e: '😓', k: 'downcast пот'),
  EmojiItem(e: '😩', k: 'weary устал'),
  EmojiItem(e: '😫', k: 'tired устал'),
  EmojiItem(e: '🥱', k: 'yawn зевает'),
  EmojiItem(e: '😤', k: 'steam nose злость пар'),
  EmojiItem(e: '😡', k: 'angry злой красный'),
  EmojiItem(e: '😠', k: 'angry злой'),
  EmojiItem(e: '🤬', k: 'cursing swear мат ругается'),
  EmojiItem(e: '😈', k: 'devil evil злодей'),
  EmojiItem(e: '👿', k: 'devil evil злодей'),
  EmojiItem(e: '💀', k: 'skull череп смерть'),
  EmojiItem(e: '💩', k: 'poop какашка'),
  EmojiItem(e: '🤡', k: 'clown клоун'),
  EmojiItem(e: '👻', k: 'ghost призрак'),
  EmojiItem(e: '👽', k: 'alien пришелец'),
  EmojiItem(e: '🤖', k: 'robot робот'),
  EmojiItem(e: '😺', k: 'cat smile кот'),
  EmojiItem(e: '😸', k: 'cat smile кот'),
  EmojiItem(e: '😹', k: 'cat laugh кот'),
  EmojiItem(e: '🙈', k: 'see no evil обезьяна не вижу'),
  EmojiItem(e: '🙉', k: 'hear no evil обезьяна не слышу'),
  EmojiItem(e: '🙊', k: 'speak no evil обезьяна молчу'),
  EmojiItem(e: '👍', k: 'thumbs up like лайк ок хорошо'),
  EmojiItem(e: '👎', k: 'thumbs down dislike дизлайк плохо'),
  EmojiItem(e: '👌', k: 'ok perfect ок супер'),
  EmojiItem(e: '🤌', k: 'pinched fingers итальянский жест'),
  EmojiItem(e: '🤏', k: 'pinching tiny чуть-чуть мало'),
  EmojiItem(e: '✌️', k: 'victory мир победа'),
  EmojiItem(e: '🤞', k: 'crossed fingers удача на удачу'),
  EmojiItem(e: '🤟', k: 'love you жест люблю'),
  EmojiItem(e: '🤘', k: 'rock horns рок метал'),
  EmojiItem(e: '🤙', k: 'call me позвони'),
  EmojiItem(e: '👈', k: 'point left влево'),
  EmojiItem(e: '👉', k: 'point right вправо'),
  EmojiItem(e: '👆', k: 'point up вверх'),
  EmojiItem(e: '👇', k: 'point down вниз'),
  EmojiItem(e: '☝️', k: 'point up вверх'),
  EmojiItem(e: '👋', k: 'wave hello bye привет пока'),
  EmojiItem(e: '🤚', k: 'hand raised рука'),
  EmojiItem(e: '🖐️', k: 'hand рука'),
  EmojiItem(e: '✋', k: 'hand stop стоп рука'),
  EmojiItem(e: '🖖', k: 'vulcan vulcan салют'),
  EmojiItem(e: '👏', k: 'clap applause аплодисменты'),
  EmojiItem(e: '🙌', k: 'raise hands руки вверх ура'),
  EmojiItem(e: '🤝', k: 'handshake рукопожатие'),
  EmojiItem(e: '🙏', k: 'pray please спасибо пожалуйста'),
  EmojiItem(e: '💪', k: 'muscle сила бицепс'),
  EmojiItem(e: '🦾', k: 'mechanical arm робот рука'),
  EmojiItem(e: '🦵', k: 'leg нога'),
  EmojiItem(e: '🦶', k: 'foot ступня'),
  EmojiItem(e: '👂', k: 'ear ухо'),
  EmojiItem(e: '👃', k: 'nose нос'),
  EmojiItem(e: '👀', k: 'eyes глаза смотрю'),
  EmojiItem(e: '👁️', k: 'eye глаз'),
  EmojiItem(e: '🧠', k: 'brain мозг ум'),
  EmojiItem(e: '🫀', k: 'heart органы сердце'),
  EmojiItem(e: '❤️', k: 'red heart любовь сердце'),
  EmojiItem(e: '🧡', k: 'orange heart сердце'),
  EmojiItem(e: '💛', k: 'yellow heart сердце'),
  EmojiItem(e: '💚', k: 'green heart сердце'),
  EmojiItem(e: '💙', k: 'blue heart сердце'),
  EmojiItem(e: '💜', k: 'purple heart сердце'),
  EmojiItem(e: '🖤', k: 'black heart сердце'),
  EmojiItem(e: '🤍', k: 'white heart сердце'),
  EmojiItem(e: '💔', k: 'broken heart разбитое сердце'),
  EmojiItem(e: '❤️‍🔥', k: 'heart fire сердце огонь'),
  EmojiItem(e: '💯', k: 'hundred 100 сто топ'),
  EmojiItem(e: '💢', k: 'anger злость'),
  EmojiItem(e: '💥', k: 'boom explosion взрыв'),
  EmojiItem(e: '💫', k: 'dizzy stars звёзды'),
  EmojiItem(e: '💦', k: 'sweat drops капли вода'),
  EmojiItem(e: '💨', k: 'dash дым бег'),
  EmojiItem(e: '🕳️', k: 'hole дыра'),
  EmojiItem(e: '💬', k: 'speech bubble речь чат'),
  EmojiItem(e: '🗨️', k: 'speech bubble чат'),
  EmojiItem(e: '🗯️', k: 'anger bubble злость'),
  EmojiItem(e: '💭', k: 'thought bubble мысли'),
  EmojiItem(e: '💤', k: 'zzz сон'),
  EmojiItem(e: '🔥', k: 'fire огонь жара'),
  EmojiItem(e: '✨', k: 'sparkles искры блеск'),
  EmojiItem(e: '⭐', k: 'star звезда'),
  EmojiItem(e: '🌟', k: 'glowing star звезда'),
  EmojiItem(e: '🎉', k: 'party popper праздник конфетти'),
  EmojiItem(e: '🎊', k: 'confetti праздник'),
  EmojiItem(e: '🎁', k: 'gift подарок'),
  EmojiItem(e: '🎈', k: 'balloon шарик'),
  EmojiItem(e: '🎂', k: 'cake торт день рождения'),
  EmojiItem(e: '🍰', k: 'cake торт'),
  EmojiItem(e: '🍕', k: 'pizza пицца'),
  EmojiItem(e: '🍔', k: 'burger бургер'),
  EmojiItem(e: '🍟', k: 'fries картошка'),
  EmojiItem(e: '🌭', k: 'hotdog хотдог'),
  EmojiItem(e: '🍿', k: 'popcorn попкорн'),
  EmojiItem(e: '🥓', k: 'bacon бекон'),
  EmojiItem(e: '🍗', k: 'chicken курица'),
  EmojiItem(e: '🍩', k: 'donut пончик'),
  EmojiItem(e: '🍪', k: 'cookie печенье'),
  EmojiItem(e: '🍫', k: 'chocolate шоколад'),
  EmojiItem(e: '🍺', k: 'beer пиво'),
  EmojiItem(e: '🍻', k: 'beers пиво'),
  EmojiItem(e: '🥂', k: 'cheers тост бокалы'),
  EmojiItem(e: '🍷', k: 'wine вино'),
  EmojiItem(e: '☕', k: 'coffee кофе'),
  EmojiItem(e: '🍵', k: 'tea чай'),
  EmojiItem(e: '🥤', k: 'drink напиток'),
  EmojiItem(e: '⚽', k: 'football футбол'),
  EmojiItem(e: '🏀', k: 'basketball баскетбол'),
  EmojiItem(e: '🏈', k: 'football american американский футбол'),
  EmojiItem(e: '⚾', k: 'baseball бейсбол'),
  EmojiItem(e: '🎾', k: 'tennis теннис'),
  EmojiItem(e: '🎮', k: 'game controller игры'),
  EmojiItem(e: '🎯', k: 'target цель'),
  EmojiItem(e: '🎲', k: 'dice кости игра'),
  EmojiItem(e: '♟️', k: 'chess шахматы'),
  EmojiItem(e: '🏆', k: 'trophy кубок победа'),
  EmojiItem(e: '🥇', k: 'gold медаль золото'),
  EmojiItem(e: '🥈', k: 'silver медаль серебро'),
  EmojiItem(e: '🥉', k: 'bronze медаль бронза'),
  EmojiItem(e: '🚀', k: 'rocket ракета полёт run'),
  EmojiItem(e: '✈️', k: 'plane самолёт'),
  EmojiItem(e: '🚗', k: 'car машина'),
  EmojiItem(e: '🚕', k: 'taxi такси'),
  EmojiItem(e: '🚌', k: 'bus автобус'),
  EmojiItem(e: '🚲', k: 'bike велосипед'),
  EmojiItem(e: '🏍️', k: 'motorcycle мотоцикл'),
  EmojiItem(e: '🚂', k: 'train поезд'),
  EmojiItem(e: '🚢', k: 'ship корабль'),
  EmojiItem(e: '⛵', k: 'sailboat лодка'),
  EmojiItem(e: '🏠', k: 'house дом'),
  EmojiItem(e: '🏢', k: 'building здание офис'),
  EmojiItem(e: '🏰', k: 'castle замок'),
  EmojiItem(e: '🗼', k: 'tower башня'),
  EmojiItem(e: '🌍', k: 'earth планета мир'),
  EmojiItem(e: '🌙', k: 'moon луна'),
  EmojiItem(e: '☀️', k: 'sun солнце'),
  EmojiItem(e: '🌈', k: 'rainbow радуга'),
  EmojiItem(e: '🌧️', k: 'rain дождь'),
  EmojiItem(e: '⛈️', k: 'storm гроза'),
  EmojiItem(e: '❄️', k: 'snow снег'),
  EmojiItem(e: '⚡', k: 'lightning молния'),
  EmojiItem(e: '🌊', k: 'wave волна'),
  EmojiItem(e: '🔥', k: 'fire огонь'),
  EmojiItem(e: '🌵', k: 'cactus кактус'),
  EmojiItem(e: '🌸', k: 'flower цветок сакура'),
  EmojiItem(e: '🌺', k: 'hibiscus цветок'),
  EmojiItem(e: '🌻', k: 'sunflower подсолнух'),
  EmojiItem(e: '🌹', k: 'rose роза'),
  EmojiItem(e: '🍀', k: 'clover клевер удача'),
  EmojiItem(e: '🍁', k: 'maple leaf лист'),
  EmojiItem(e: '🎃', k: 'pumpkin тыква хэллоуин'),
  EmojiItem(e: '👑', k: 'crown корона'),
  EmojiItem(e: '💎', k: 'gem бриллиант'),
  EmojiItem(e: '💰', k: 'money bag деньги'),
  EmojiItem(e: '💸', k: 'money fly деньги'),
  EmojiItem(e: '📱', k: 'phone телефон'),
  EmojiItem(e: '💻', k: 'laptop компьютер'),
  EmojiItem(e: '⌨️', k: 'keyboard клавиатура'),
  EmojiItem(e: '🖥️', k: 'monitor монитор'),
  EmojiItem(e: '🖱️', k: 'mouse мышь'),
  EmojiItem(e: '🔔', k: 'bell звонок'),
  EmojiItem(e: '🔕', k: 'bell off без звука'),
  EmojiItem(e: '📢', k: 'loudspeaker громкоговоритель'),
  EmojiItem(e: '📣', k: 'megaphone мегафон'),
  EmojiItem(e: '🔒', k: 'lock замок закрыто'),
  EmojiItem(e: '🔓', k: 'unlock открыто'),
  EmojiItem(e: '🔑', k: 'key ключ'),
  EmojiItem(e: '🛡️', k: 'shield щит защита'),
  EmojiItem(e: '⚔️', k: 'swords мечи'),
  EmojiItem(e: '🗡️', k: 'dagger кинжал'),
  EmojiItem(e: '🔫', k: 'gun пистолет'),
  EmojiItem(e: '💣', k: 'bomb бомба'),
  EmojiItem(e: '🎯', k: 'target цель'),
  EmojiItem(e: '🔧', k: 'wrench ключ инструмент'),
  EmojiItem(e: '🔨', k: 'hammer молоток'),
  EmojiItem(e: '🛠️', k: 'tools инструменты'),
  EmojiItem(e: '📚', k: 'books книги'),
  EmojiItem(e: '📖', k: 'book книга'),
  EmojiItem(e: '✏️', k: 'pencil карандаш'),
  EmojiItem(e: '📝', k: 'memo заметка'),
  EmojiItem(e: '📌', k: 'pin булавка'),
  EmojiItem(e: '📎', k: 'paperclip скрепка'),
  EmojiItem(e: '✂️', k: 'scissors ножницы'),
  EmojiItem(e: '🧹', k: 'broom метла уборка'),
  EmojiItem(e: '🧽', k: 'sponge губка'),
  EmojiItem(e: '🛒', k: 'cart тележка покупки'),
  EmojiItem(e: '🎵', k: 'note музыка'),
  EmojiItem(e: '🎶', k: 'notes музыка'),
  EmojiItem(e: '🎧', k: 'headphones наушники'),
  EmojiItem(e: '🎤', k: 'mic микрофон'),
  EmojiItem(e: '🎸', k: 'guitar гитара'),
  EmojiItem(e: '🥁', k: 'drum барабан'),
  EmojiItem(e: '🎹', k: 'piano пианино'),
  EmojiItem(e: '🎬', k: 'clapper кино фильм'),
  EmojiItem(e: '🎥', k: 'camera камера кино'),
  EmojiItem(e: '📷', k: 'camera фото'),
  EmojiItem(e: '📸', k: 'camera flash фото'),
  EmojiItem(e: '🖼️', k: 'picture картина'),
  EmojiItem(e: '🎨', k: 'palette палитра искусство'),
  EmojiItem(e: '🧩', k: 'puzzle пазл'),
  EmojiItem(e: '🚦', k: 'traffic light светофор'),
  EmojiItem(e: '🏁', k: 'flag флаг финиш'),
  EmojiItem(e: '🎗️', k: 'ribbon лента'),
  EmojiItem(e: '🧿', k: 'nazar амулет глаз'),
  EmojiItem(e: '🫡', k: 'salute честь'),
  EmojiItem(e: '🫠', k: 'melting тает'),
  EmojiItem(e: '🫣', k: 'peek подсматривает'),
  EmojiItem(e: '🥹', k: 'tears smile слёзы улыбка'),
  EmojiItem(e: '❤️‍🩹', k: 'heart healing сердце'),
  EmojiItem(e: '😮‍💨', k: 'exhale выдох'),
  EmojiItem(e: '🤗', k: 'hug объятия'),
  EmojiItem(e: '🤩', k: 'star eyes восторг'),
];

List<EmojiItem> searchEmojis(String query, [int limit = 80]) {
  final q = query.trim().toLowerCase();
  if (q.isEmpty) return emojis.take(limit).toList();
  return emojis.where((it) => it.k.toLowerCase().contains(q)).take(limit).toList();
}
